Repository somle2005/ruoyi-vue-pro, pull requests merged in 2025-02, with the labels that each got.

#46 fix getBodyString使用 try-with-resources，确保 ResponseBody 资源被正确关闭，避免资源泄露。
  somle-framework/somle-common/src/main/java/com/somle/framework/common/util/web/WebUtils.java
Labels: question

#45 feature 重构ERP(产品+海关规则)+增加产品同步定时任务
  somle-esb/src/main/java/com/somle/esb/converter/ErpToEccangConverter.java
  somle-esb/src/main/java/com/somle/esb/converter/ErpToKingdeeConverter.java
  somle-esb/src/main/java/com/somle/esb/handler/ErpCustomRuleHandler.java
  somle-esb/src/main/java/com/somle/esb/handler/ErpProductHandler.java
  somle-esb/src/test/java/com/somle/esb/job/SyncErpProductJobTest.java
  somle-esb/src/test/java/com/somle/esb/service/EsbServiceProductTest.java
  somle-framework/somle-common/src/main/java/com/somle/framework/common/util/number/LengthUtils.java
  yudao-module-erp/yudao-module-erp-api/src/main/java/cn/iocoder/yudao/module/erp/api/logistic/customrule/ErpCustomRuleApi.java
  yudao-module-erp/yudao-module-erp-api/src/main/java/cn/iocoder/yudao/module/erp/api/logistic/customrule/dto/ErpCustomRuleDTO.java
  yudao-module-erp/yudao-module-erp-api/src/main/java/cn/iocoder/yudao/module/erp/api/product/ErpProductApi.java
  yudao-module-erp/yudao-module-erp-api/src/main/java/cn/iocoder/yudao/module/erp/api/product/dto/ErpCustomRuleDTO.java
  yudao-module-erp/yudao-module-erp-api/src/main/java/cn/iocoder/yudao/module/erp/api/product/dto/ErpProductDTO.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/api/logistic/ErpCustomRuleApiImpl.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/api/product/ErpProductApiImpl.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/controller/admin/logistic/customrule/vo/ErpCustomRuleRespVO.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/convert/logistic/ErpCustomRuleConvert.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/convert/product/ErpProductConvert.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/dal/mysql/logistic/customrule/ErpCustomRuleMapper.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/service/logistic/customrule/ErpCustomRuleService.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/service/logistic/customrule/ErpCustomRuleServiceImpl.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/service/product/ErpProductService.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/service/product/ErpProductServiceDelegator.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/service/product/ErpProductServiceImpl.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/service/purchase/ErpSupplierProductServiceImpl.java
Labels: invalid

#52 fix 修复金蝶报警问题。默认覆盖已存在产品。
  somle-esb/src/main/java/com/somle/esb/converter/ErpToKingdeeConverter.java
  somle-esb/src/main/java/com/somle/esb/handler/ErpCustomRuleHandler.java
  somle-esb/src/main/java/com/somle/esb/handler/ErpProductHandler.java
  somle-esb/src/main/java/com/somle/esb/handler/ErpSupplierHandler.java
  somle-kingdee/src/main/java/com/somle/kingdee/model/KingdeeProductSaveReqVO.java
  somle-kingdee/src/main/java/com/somle/kingdee/service/KingdeeClient.java
  somle-kingdee/src/main/java/com/somle/kingdee/service/KingdeeService.java
Labels: question

#51 erp增加管理后台 - 海关分类菜单
  yudao-framework/yudao-spring-boot-starter-biz-tenant/src/main/java/cn/iocoder/yudao/framework/tenant/core/db/TenantBaseDO.java
  yudao-module-erp/yudao-module-erp-api/src/main/java/cn/iocoder/yudao/module/erp/enums/ErrorCodeConstants.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/controller/admin/logistic/category/ErpCustomCategoryController.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/controller/admin/logistic/category/item/ErpCustomCategoryItemController.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/controller/admin/logistic/category/item/vo/ErpCustomCategoryItemPageReqVO.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/controller/admin/logistic/category/item/vo/ErpCustomCategoryItemRespVO.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/controller/admin/logistic/category/item/vo/ErpCustomCategoryItemSaveReqVO.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/controller/admin/logistic/category/item/vo/ErpCustomCategoryItemSimpleRespVO.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/controller/admin/logistic/category/vo/ErpCustomCategoryPageReqVO.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/controller/admin/logistic/category/vo/ErpCustomCategoryRespVO.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/controller/admin/logistic/category/vo/ErpCustomCategorySaveReqVO.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/controller/admin/tool/Validation.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/convert/logistic/category/ErpCustomCategoryConvert.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/convert/logistic/category/item/ErpCustomCategoryItemConvert.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/dal/dataobject/logistic/category/ErpCustomCategoryDO.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/dal/dataobject/logistic/category/item/ErpCustomCategoryItemDO.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/dal/mysql/logistic/category/ErpCustomCategoryMapper.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/dal/mysql/logistic/category/item/ErpCustomCategoryItemMapper.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/service/logistic/category/ErpCustomCategoryService.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/service/logistic/category/ErpCustomCategoryServiceImpl.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/service/logistic/category/bo/ErpCustomCategoryBO.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/service/logistic/category/item/ErpCustomCategoryItemService.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/service/logistic/category/item/ErpCustomCategoryItemServiceImpl.java
  yudao-module-erp/yudao-module-erp-biz/src/test/java/cn/iocoder/yudao/module/erp/service/logistic/category/ErpCustomCategoryServiceImplTest.java
  yudao-module-erp/yudao-module-erp-biz/src/test/java/cn/iocoder/yudao/module/erp/service/logistic/category/item/ErpCustomCategoryItemServiceImplTest.java
  yudao-module-erp/yudao-module-erp-biz/src/test/java/cn/iocoder/yudao/module/erp/service/logistic/customrule/ErpCustomRuleServiceImplTest.java
Labels: enhancement

#48 erp产品的查询增加 查询入参
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/controller/admin/product/ErpProductController.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/controller/admin/product/vo/product/ErpProductPageReqVO.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/dal/mysql/product/ErpProductMapper.java
Labels: enhancement

#54 fix: 增加产品材质（产品信息的属性）
  somle-amazon/src/test/java/com/somle/amazon/service/AmazonAdClientTest.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/controller/admin/product/ErpProductController.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/controller/admin/product/vo/product/ErpProductPageReqVO.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/controller/admin/product/vo/product/ErpProductRespVO.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/controller/admin/product/vo/product/ErpProductSaveReqVO.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/controller/admin/product/vo/product/ErpProductSimpleRespVO.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/dal/dataobject/product/ErpProductDO.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/dal/mysql/product/ErpProductMapper.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/service/product/bo/ErpProductBO.java
Labels: enhancement

#60 feature 使用注解来防止重复提交、默认1s内防止提交重复数据。实现post接口幂等性。
  yudao-framework/yudao-spring-boot-starter-protection/src/main/java/cn/iocoder/yudao/framework/idempotent/core/aop/IdempotentAspect.java
  yudao-module-erp/yudao-module-erp-biz/pom.xml
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/controller/admin/logistic/category/ErpCustomCategoryController.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/controller/admin/logistic/category/item/vo/ErpCustomCategoryItemSaveReqVO.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/controller/admin/logistic/customrule/ErpCustomRuleController.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/controller/admin/product/ErpProductCategoryController.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/controller/admin/product/ErpProductController.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/controller/admin/product/ErpProductUnitController.java
  yudao-module-erp/yudao-module-erp-biz/src/main/java/cn/iocoder/yudao/module/erp/service/logistic/category/ErpCustomCategoryServiceImpl.java
Labels: enhancement

#63 BUG 同步单位替换，修改默认单位CNY，申报单位USD
  somle-esb/src/main/java/com/somle/esb/converter/ErpToEccangConverter.java
  somle-esb/src/main/java/com/somle/esb/handler/DepartmentHandler.java
  somle-esb/src/main/java/com/somle/esb/handler/DingtalkDepartmentHandler.java
  somle-esb/src/main/java/com/somle/esb/handler/DingtalkUserHandler.java
  somle-esb/src/main/java/com/somle/esb/handler/EccangSaleHandler.java
  somle-esb/src/main/java/com/somle/esb/handler/ErpCustomRuleHandler.java
  somle-esb/src/main/java/com/somle/esb/handler/ErpProductHandler.java
  yudao-module-erp/yudao-module-erp-biz/src/test/java/cn/iocoder/yudao/module/erp/service/logistic/category/ErpCustomCategoryServiceImplTest.java
Labels: bug

#68 update 解决编译问题
  yudao-framework/yudao-common/src/main/java/cn/iocoder/yudao/framework/common/util/json/JsonUtils.java
Labels: bug

#69 update YudaoJacksonAutoConfiguration 回退调试用的代码
  yudao-framework/yudao-spring-boot-starter-web/src/main/java/cn/iocoder/yudao/framework/jackson/config/YudaoJacksonAutoConfiguration.java
Labels: bug
